"""add categoria relationship to subcategoria

Revision ID: 309135bf1d87
Revises: b80a19a4188f
Create Date: 2025-07-31 21:10:50.736681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309135bf1d87'
down_revision = 'b80a19a4188f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('temp_subcategoria_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))
        batch_op.alter_column('correo',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_subcategoria_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
